### PR TITLE
Merge in latest JuliaLang/julia `master` && resolve conflicts

### PR DESCRIPTION
**Pull request by NHDaly**
This PR just updates your PR https://github.com/JuliaLang/julia/pull/23426 to merge in `master` and resolve the conflicts. The `@inferred` API has changed some, so this updates the PR to reflect that, and updates the tests (since the test file moved).

EDIT:
Hrmmm sadly the diff from this merge is huge.... Lemme just paste the diff from `git diff origin/master` so you can see what the new PR would look like if you merge this in:

```diff
diff --git a/NEWS.md b/NEWS.md
index fc1aa9edc1..b91690b970 100644
--- a/NEWS.md
+++ b/NEWS.md
@@ -52,6 +52,12 @@ Standard library changes
 * Since environment variables on Windows are case-insensitive, `ENV` now converts its keys
   to uppercase for display, iteration, and copying ([#30593]).
 
+#### Test
+
+* The new `@isinferred` macro does the same as `@inferred` but returns a boolean
+  rather than throwing an exception.
+
+
 External dependencies
 ---------------------
 
diff --git a/stdlib/Test/src/Test.jl b/stdlib/Test/src/Test.jl
index 3d8a76a281..24dc6fbf04 100644
--- a/stdlib/Test/src/Test.jl
+++ b/stdlib/Test/src/Test.jl
@@ -19,7 +19,7 @@ export @test, @test_throws, @test_broken, @test_skip,
 
 export @testset
 # Legacy approximate testing functions, yet to be included
-export @inferred
+export @inferred, @isinferred
 export detect_ambiguities, detect_unbound_args
 export GenericString, GenericSet, GenericDict, GenericArray, GenericOrder
 export TestSetException
@@ -1337,6 +1337,90 @@ macro inferred(allow, ex)
     _inferred(ex, __module__, allow)
 end
 function _inferred(ex, mod, allow = :(Union{}))
+    # @inferred performs almost the same checks as @code_warntype except for some
+    # corner cases in which the return value is a type and is not inferred
+    # correctly, e.g.
+    # f() = [DataType][1]
+    # g() = [Int64][1]
+    # @inferred throws an exception for f and g, but @code_warntype
+    # does not complain
+    inference = _inferred_impl(ex, mod)
+    quote
+        let
+            allow = $(esc(allow))
+            allow isa Type || throw(ArgumentError("@inferred requires a type as second argument"))
+            let (rettype, inftypes, result) = $inference
+                rettype <: allow || rettype == typesubtract(inftypes[1], allow) || error("return type $rettype does not match inferred return type $(inftypes[1])")
+                result
+            end
+        end
+    end
+end
+
+"""
+    @isinferred [AllowedType] f(x)
+
+Checks whether the call expression `f(x)` is type stable and returns a
+boolean value. `@isinferred` is similar to `@inferred`,
+but returns a boolean rather than throwing an exception.
+This macro is useful for unit tests (`@test @isinferred f(x)`).
+
+Optionally, `AllowedType` relaxes the test, by making it pass when either the type of `f(x)`
+matches the inferred type modulo `AllowedType`, or when the return type is a subtype of
+`AllowedType`. This is useful when testing type stability of functions returning a small
+union such as `Union{Nothing, T}` or `Union{Missing, T}`.
+
+`f(x)` can be any call expression.
+
+```jldoctest
+julia> using Base.Test
+
+julia> f(a,b,c) = b > 1 ? 1 : 1.0
+f (generic function with 1 method)
+
+julia> @code_warntype f(1,2,3)
+Variables:
+  #self#::#f
+  a::Int64
+  b::Int64
+  c::Int64
+
+Body:
+  begin
+      unless (Base.slt_int)(1, b::Int64)::Bool goto 3
+      return 1
+      3:
+      return 1.0
+  end::UNION{FLOAT64, INT64}
+
+julia> @isinferred f(1,2,3)
+false
+
+julia> @isinferred max(1,2)
+false
+```
+"""
+macro isinferred(ex)
+    _isinferred(ex, __module__)
+end
+macro isinferred(allow, ex)
+    _isinferred(ex, __module__, allow)
+end
+function _isinferred(ex, mod, allow = :(Union{}))
+    # @isinferred performs the same checks as @inferred
+    inference = _inferred_impl(ex, mod)
+    quote
+        let
+            allow = $(esc(allow))
+            allow isa Type || throw(ArgumentError("@inferred requires a type as second argument"))
+            let (rettype, inftypes, result) = $inference
+                rettype <: allow || rettype == typesubtract(inftypes[1], allow)
+            end
+        end
+    end
+end
+
+function _inferred_impl(ex, __module__)
     if Meta.isexpr(ex, :ref)
         ex = Expr(:call, :getindex, ex.args...)
     end
@@ -1349,8 +1433,6 @@ function _inferred(ex, mod, allow = :(Union{}))
     end
     Base.remove_linenums!(quote
         let
-            allow = $(esc(allow))
-            allow isa Type || throw(ArgumentError("@inferred requires a type as second argument"))
             $(if any(a->(Meta.isexpr(a, :kw) || Meta.isexpr(a, :parameters)), ex.args)
                 # Has keywords
                 args = gensym()
@@ -1369,8 +1451,7 @@ function _inferred(ex, mod, allow = :(Union{}))
             end)
             @assert length(inftypes) == 1
             rettype = result isa Type ? Type{result} : typeof(result)
-            rettype <: allow || rettype == typesubtract(inftypes[1], allow) || error("return type $rettype does not match inferred return type $(inftypes[1])")
-            result
+            rettype, inftypes, result
         end
     end)
 end
diff --git a/stdlib/Test/test/runtests.jl b/stdlib/Test/test/runtests.jl
index a26cf54b59..97be750dfa 100644
--- a/stdlib/Test/test/runtests.jl
+++ b/stdlib/Test/test/runtests.jl
@@ -521,8 +521,17 @@ uninferrable_small_union(i) = (1, nothing)[i]
 @test_throws ErrorException @inferred(Missing, uninferrable_small_union(1))
 @test_throws ErrorException @inferred(Missing, uninferrable_small_union(2))
 @test_throws ArgumentError @inferred(nothing, uninferrable_small_union(1))
+# test @isinferred w/ same tests as above
+@test !@isinferred(uninferrable_function(1))
+@test @isinferred(identity(1))
+@test @isinferred(Nothing, uninferrable_small_union(1))
+@test @isinferred(Nothing, uninferrable_small_union(2))
+@test !@isinferred(Missing, uninferrable_small_union(1))
+@test !@isinferred(Missing, uninferrable_small_union(2))
+@test_throws ArgumentError @isinferred(nothing, uninferrable_small_union(1))
 
-# Ensure @inferred only evaluates the arguments once
+
+# Ensure @inferred and @isinferred only evaluate the arguments once
 inferred_test_global = 0
 function inferred_test_function()
     global inferred_test_global
@@ -531,26 +540,34 @@ function inferred_test_function()
 end
 @test @inferred inferred_test_function()
 @test inferred_test_global == 1
+@test @isinferred inferred_test_function()
+@test inferred_test_global == 2
 
 struct SillyArray <: AbstractArray{Float64,1} end
 Base.getindex(a::SillyArray, i) = rand() > 0.5 ? 0 : false
 @testset "@inferred works with A[i] expressions" begin
     @test (@inferred (1:3)[2]) == 2
+    @test @isinferred((1:3)[2])
     test_result = @test_throws ErrorException (@inferred SillyArray()[2])
     @test occursin("Bool", test_result.value.msg)
+    @test !@isinferred(SillyArray()[2])
 end
 # Issue #14928
 # Make sure abstract error type works.
 @test_throws Exception error("")
 
 # Issue #17105
-# @inferred with kwargs
+# @inferred and @isinferred with kwargs
 inferrable_kwtest(x; y=1) = 2x
 uninferrable_kwtest(x; y=1) = 2x+y
 @test (@inferred inferrable_kwtest(1)) == 2
 @test (@inferred inferrable_kwtest(1; y=1)) == 2
 @test (@inferred uninferrable_kwtest(1)) == 3
 @test (@inferred uninferrable_kwtest(1; y=2)) == 4
+@test @isinferred(inferrable_kwtest(1))
+@test @isinferred(inferrable_kwtest(1; y=1))
+@test @isinferred(uninferrable_kwtest(1))
+@test !@isinferred(uninferrable_kwtest(1; y=2))
 
 @test_throws ErrorException @testset "$(error())" for i in 1:10
 end
```

### CODE REVIEW

**Comment by ghost** [comment]
EDIT: I've pasted the git diff into the top OP commit. (Sorry i'm posting from two different accounts accidentally... >.<

**Comment by NHDaly** [comment]
Friendly ping! This should be a simple merge, that just brings your PR up to date! :)

Let me know if you have any questions. :)

**Comment by afniedermayer** [comment]
Thanks! I'll try to do it over the weekend

Nathan Daly <notifications@github.com> schrieb am Do., 7. März 2019, 20:09:

**Review by afniedermayer — APPROVED** [review]

**Comment by afniedermayer** [comment]
@NHDaly thanks a lot for taking care of this and sorry for the delay, I now merged your changes into this branch. Can the pull request be now merged into JuliaLang/julia or do I need to do something more?

**Comment by NHDaly** [comment]
> @NHDaly thanks a lot for taking care of this and sorry for the delay, I now merged your changes into this branch. 
😁  I'm glad to help! :) Thanks for merging!

> Can the pull request be now merged into JuliaLang/julia or do I need to do something more?

I'm not sure. I'm not a maintainer myself, i just wanted to see this PR get merged. You should ping the original PR and ask for people's opinions there! :)

**Pull request merged**
